FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["SnakeHub/SnakeHub.csproj", "SnakeHub/"]
RUN dotnet restore "SnakeHub/SnakeHub.csproj"
COPY . .
WORKDIR "/src/SnakeHub"
RUN dotnet build "SnakeHub.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SnakeHub.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SnakeHub.dll"]
