using System.ComponentModel;

namespace SnakeHub.Enums
{
    public enum Icon
    {
        [Description("award-fill")]
        AWARD,
        [Description("book-fill")]
        BOOK,
        [Description("cloud-fill")]
        CLOUD,
        [Description("droplet-fill")]
        DROPLET,
        [Description("eye-fill")]
        EYE,
        [Description("flag-fill")]
        FLAG,
        [Description("gift-fill")]
        GIFT,
        [Description("heart-fill")]
        HEART,
        [Description("image-alt")]
        IMAGE,
        [Description("joystick")]
        JOYSTICK,
        [Description("key-fill")]
        KEY,
        [Description("lightning-fill")]
        LIGHTNING,
        [Description("moon-fill")]
        MOON,
        [Description("nut-fill")]
        NUT,
        [Description("octagon-fill")]
        OCTAGON,
        [Description("puzzle-fill")]
        PUZZLE,
        [Description("question")]
        QUESTION,
        [Description("rulers")]
        RULERS,
        [Description("sun-fill")]
        SUN,
        [Description("tree-fill")]
        TREE,
        [Description("umbrella-fill")]
        UMBRELLA,
        [Description("vector-pen")]
        VECTORPEN,
        [Description("wrench")]
        WRENCH,
        [Description("x-diamond-fill")]
        XDIAMOND,
        [Description("youtube")]
        YOUTUBE,
        [Description("zoom-in")]
        ZOOMIN,
    }
}
